### PR TITLE
Respect the XDG base directory specification

### PR DESCRIPTION
**Pull request by linkmauve**
This requires the user to manually move their configuration and data if they already have some, if that’s unacceptable I can add a check for the current location first, then a fallback to the correct behaviour.

### CODE REVIEW

**Comment by marcan** [comment]
This is fine, I meant to make this change too. While we're breaking existing setups, can you rename "cfg" to "config"? I never liked the short name :) (or feel free to propose a better name).

docs/blitzberry.md needs an update for the new paths.

**Comment by linkmauve** [comment]
What about blitzloop.conf? It sounds a bit better to me (especially when people share it alone), and is more in line with other programs I have here.

**Comment by marcan** [comment]
blitzloop.conf sounds good to me.

**Comment by linkmauve** [comment]
Changed the file name, added documentation in docs/blitzberry.md, renamed example.cfg to example.conf too.

**Pull request merged**
