### PR TITLE
Now with 100% more installable code.

### PR DESCRIPTION
**Pull request by yacoob**
Tested the procedure on both OSX and Linux, seems to result in a correctly installed blitzloop instance. Unless I'm hallucinating from the fever :D 

This depends on https://github.com/marcan/pympv/pull/2 - or rather, the INSTALL.md is written assuming that PR has been merged.

### CODE REVIEW

**Comment by marcan** [comment]
Some things as I find them:

* run.sh still has the old path.
* hand_and_tablet.svg should be moved out of the resources; it's a source file (to generate the PNGs) and thus not needed for operation.

**Comment by marcan** [comment]
* add build/ to .gitignore (and .eggs, and *.egg-info)
* _audio gets installed in the root, it should be under the blitzloop module

**Comment by marcan** [comment]
Other than those nits this seems to do the right things, so this is ready to merge once those are fixed :)

Thanks for setting this up. Should make management of "standalone" instances a lot nicer (previously any dep changes would break everything; a virtualenv should fix that)

**Comment by yacoob** [comment]
PTAL? I was thinking how I can make `run.sh` still work for existing setups, but I don't see a sensible way of doing so - manual effort to go from py2 to py3 is required anyway.

**Comment by marcan** [comment]
LGTM. I just wanted run.sh to not be blatantly broken (or, alternatively, have it removed); I'm okay with breaking everything at this point, part of the point of this ordeal is to make future breakage less likely.

**Pull request merged**
